Lab/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('lab_01/', include('lab_01.urls')),
    path('lab_02/', include('lab_02.urls')),
    path('lab_03/', include('lab_03.urls')),
    path('lab_04/', include('lab_04.urls')),
    path('lab_05/', include('lab_05.urls')),
]

lab_03/urls.py
from django.urls import path
from . import views

app_name = "lab_03"

urlpatterns = [
    path('', views.home, name="home_page"),
    path('blog/', views.blog, name="blog"),
    path('signup/', views.signup, name="signup"),
]

lab_03/models.py
from django.db import models

# Create your models here.

lab_03/views.py
from django.shortcuts import render

def home(request):
    response = {
        "title"     : "Welcome to My Page",
        "navs"      : {
            "Home"      : "#home",
            "Profile"   : "#profile",
            "Skills"    : "#skills",
            "Projects"  : "#projects",
            "Contacts"  : "#contacts",
            "Sign Up!"  : "signup"
        },
        "footer"    : "Copyright of Jonathanjojo"
    }
    return render(request, 'lab_03/home.html', response)

def blog(request):
    response = {
        "title"     : "Future Texts",
        "navs"      : {
        },
        "footer"    : ""
    }
    return render(request, 'lab_03/blog.html', response)

def signup(request):
    response = {
        "title"     : "Sign Me UP!",
        "navs"      : {
            "Home"      : "../",
            "Sign Up!"  : "#signup"
        },
        "footer"    : "Copyright of Jonathanjojo"
    }
    return render(request, 'lab_03/signup.html', response)

lab_03/templates/lab_03/blog.html
{% extends 'lab_03/base_layout.html' %}

{% load static from staticfiles %}

{% block content %}

    <header class="container">
        <div class="d-flex">
            <div>
                <h1 class="white-text bolder blog-title">FUTURE TEXTS</h1>
                <h4 class="hnl-red-text">Living Writings of Jonathan Christopher Jakub</h4>
                <h5 class="light-grey-text">A web-developing lover, tech-growing enthusiast</h5>
            </div>
            <a href="{% url 'lab_03:home_page' %}" class="ml-auto"><img class="home-link-img" src="{% static 'lab_03/img/home-button.png' %}"></a>
        </div>
    </header>
    <div class="w-100 container align-items-center first-top">
        <div class="card transparent-bg rounded-edge light-grey-border article-card">
            <div class="card-body">
                <h5 class="card-title white-text bold">A New Sight of Future Web-Developing</h5>
                <h6 class="card-subtitle mb-2 text-muted">Sunday, 2018 Sept 2</h6>
                <p class="card-text white-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt 
                    ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco 
                    laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in 
                    voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
                    non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
                <a href="#" class="card-link bold hnl-red-text">Read more ...</a>
            </div>
        </div>

        <div class="card transparent-bg rounded-edge light-grey-border article-card">
            <div class="card-body">
                <h5 class="card-title white-text bold">A Web-Developer Guide to Greatness</h5>
                <h6 class="card-subtitle mb-2 text-muted">Sunday, 2018 Aug 5</h6>
                <p class="card-text white-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt 
                    ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco 
                    laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in 
                    voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
                    non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
                <a href="#" class="card-link bold hnl-red-text">Read more ...</a>
            </div>
        </div>

        <div class="card transparent-bg rounded-edge light-grey-border article-card">
            <div class="card-body">
                <h5 class="card-title white-text bold">Story of a Little Portfolio</h5>
                <h6 class="card-subtitle mb-2 text-muted">Sunday, 2018 July 1</h6>
                <p class="card-text white-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt 
                    ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco 
                    laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in 
                    voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat 
                    non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
                <a href="#" class="card-link bold hnl-red-text">Read more ...</a>
            </div>
        </div>    
    </div>
    <footer>
        <nav class="pagination-nav-bar" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link transparent-border" href="#" aria-label="Previous">
                        <span class="light-grey-text"aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link hnl-red-text transparent-border" href="#">1</a></li>
                <li class="page-item">
                    <a class="page-link transparent-border" href="#" aria-label="Next">
                        <span class="light-grey-text"aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </nav>
    </footer>

{% endblock %}

lab_03/templates/lab_03/home.html
{% extends 'lab_03/base_layout.html' %}

{% load static from staticfiles %}

{% block content %}
    
    <div class="w-100 full-height home-section-wrapper d-flex align-items-center main" id="home">
        <section class="container">
            <h1 class="light-grey-text bold page-title">Professional Full-Stack Web Developer.</h1>
            <h3 class="light-grey-text home-desc">
                I design and code amazing websites, and I love what I do. 
                If you are interested in me, this is the place to go. 
                You can find out more about my kind of web-developing <a class="in-text-link hnl-red-text" href="{% url 'lab_03:blog' %}">here</a>.
            </h3>
            <a href="#profile" class="btn hnl-red-bg btn-lg home-nav-btn dark-grey-text text-left" tabindex="-1" role="button" aria-disabled="true">I want to know more <span class="bold"> ></span></a>
            <a href="#contacts" class="btn light-grey-bg btn-lg home-nav-btn dark-grey-text text-left" tabindex="-1" role="button" aria-disabled="true">I'm looking for hire <span class="bold"> ></span></a>
        </section>
    </div>
    
    <div class="w-100 full-height white-bg d-flex align-items-center section-wrapper">
        <section class="container" id="profile">
            <div class="text-center">
                <img src="{% static 'lab_03/img/profile-pic.jpg' %}" class="img-responsive rounded-circle profile-pic" alt="Profile Picture">
                <h2 class="hnl-red-text">Hello, I'm Jojo. Nice to meet you.</h2>
                <h4 class="dark-grey-text">Since beginning my journey as a web designer, I've done intense trainings in web-developing, 
                    and collaborated with talented people to create digital products for both business and consumer use. 
                    I'm active, energetic, and passionate at what I'm doing.</h4>
            </div>
        </section>
    </div>

    <div class="w-100 full-height light-grey-bg d-flex align-items-center section-wrapper">
        <section class="container" id="skills">
            <h3 class="dark-grey-text text-center section-title">Acquired Skills</h3>
            <div class="text-center">
                <div class="row">
                    <div class="col-md-4">
                        <div class="card hnl-red-border white-bg">
                            <div class="card-body">
                                <h4 class="card-title hnl-red-text">Back-End Developer</h4>
                                <p class="card-text">
                                    <p>I love designing and coding web apps structure.</p>
                                    <p><h5 class="hnl-red-text">Framework I used</h5></p>
                                    <p>Django</p>
                                    <p>Rails</p>
                                    <p>Laravel</p>
                                    <p><h5 class="hnl-red-text">Tools I used</h5></p>
                                    <p>Docker</p>
                                    <p>Databases</p>
                                    <p>Various Editors</p>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card hnl-red-border white-bg">
                            <div class="card-body">
                                <h4 class="card-title hnl-red-text">Front-End Developer</h4>
                                <p class="card-text">
                                    <p>I enjoy creating marvelous UI/UX for my well-designed web apps</p>
                                    <p><h5 class="hnl-red-text">Languages I used</h5></p>
                                    <p>HTML</p>
                                    <p>CSS</p>
                                    <p>Javascript</p>
                                    <p><h5 class="hnl-red-text">Tools I used</h5></p>
                                    <p>Wireframe</p>
                                    <p>Marvelapp</p>
                                    <p>Various Editors</p>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card hnl-red-border white-bg">
                            <div class="card-body">
                                <h4 class="card-title hnl-red-text">Mentor</h4>
                                <p class="card-text">
                                    <p>I like teaching and sharing my knowledge to my juniors.</p>
                                    <p><h5 class="hnl-red-text">Where I teach</h5></p>
                                    <p>Faculty of Computer Science</p>
                                    <p>University of Indonesia</p>
                                    <p>2018</p>
                                    <p><h5 class="hnl-red-text">Mentoring Experiences</h5></p>
                                    <p>300+ juniors</p>
                                    <p>20+ mentors</p>
                                    <p>500+ work hours</p>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>           
            </div>
        </section>
    </div>
    
    <div class="w-100 full-height white-bg d-flex align-items-center section-wrapper">
        <section class="container" id="projects">
            <h3 class="dark-grey-text text-center section-title">Projects</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'lab_03/img/projects/project1.jpg' %}" alt="Project#1">
                        <div class="card-body">
                            <h5 class="card-title bold">Portfolio Website</h5>
                            <p class="card-text">
                                This is my latest project. I have been working on this project since the
                                beginning of the second semester of 2018. I have done the research and designing
                                steps. I need to code it to produce a beautiful Portfolio
                                website that everyone can easily access.
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'lab_03/img/projects/project2.jpg' %}" alt="Project#2">
                        <div class="card-body">
                            <h5 class="card-title bold">Line Bot Integrated Website</h5>
                            <p class="card-text">
                                This is my previous project. I almost finish this project and I am intending to
                                finish it by the end of this semester. I designed the apps, classes, maps, and 
                                object parsings. I also incorporated the app with a Line Bot to enrich and ease 
                                users to access my app.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="w-100 height-90 light-grey-bg d-flex align-items-center section-wrapper">
        <section class="container" id="contacts">
            <div class="text-center">
                <h3 class="dark-grey-text section-title">Contact<span class="hnl-red-text">ME</span></h3>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <ul class="d-flex list-unstyled social-medias">
                        <li><a href="https://mail.google.com" target="_blank"><img class="media-link-img" src="{% static 'lab_03/img/social-medias/mail.png' %}"></a></li>
                        <li><a href="https://github/Jonathanjojo19" target="_blank"><img class="media-link-img" src="{% static 'lab_03/img/social-medias/github.png' %}"></a></li>
                        <li><a href="https://id.linkedin.com/in/jonathan-christopher-aba556164" target="_blank"><img class="media-link-img" src="{% static 'lab_03/img/social-medias/linkedin.png' %}"></a></li>
                        <li><a href="https://twitter.com/jonathanjojo_19" target="_blank"><img class="media-link-img" src="{% static 'lab_03/img/social-medias/twitter.png' %}"></a></li>
                    </ul>
                </div>

                <div class="col-md-10">
                    <form class="feedback-form">
                        <div class="form-group row">
                            <label for="inputName" class="col-2 col-md-3 col-form-label text-right bold hnl-red-text">Name</label>
                            <div class="col-10 col-md-9">
                            <input type="text" class="form-control hnl-red-border" id="inputName" placeholder="Your Name">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail" class="col-2 col-md-3 col-form-label text-right bold hnl-red-text">Email</label>
                            <div class="col-10 col-md-9">
                            <input type="email" class="form-control hnl-red-border" id="inputEmail" placeholder="Your Email">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputMessage" class="col-2 col-md-3 col-form-label text-right bold hnl-red-text">Message</label>
                            <div class="col-10 col-md-9">
                            <textarea class="form-control hnl-red-border" id="inputMessage" placeholder="Your Message"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-10 col-md-9 ml-auto">
                                <button type="submit" class="btn btn-primary hnl-red-text white-bg hnl-red-border submit-btn">Send!</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <p class="text-center personal-quote">Living, Learning, Loving</p>
        </section>
    </div>

{% endblock %}

lab_03/templates/lab_03/signup.html
{% extends 'lab_03/base_layout.html' %}

{% load static from staticfiles %}

{% block content %}
    <div class="w-100 height-90 black-bg d-flex align-items-center section-wrapper">
        <section class="container main" id="signup">
            <div class="text-center">
                <h3 class="light-grey-text section-title">Sign<span class="hnl-red-text">UP!</span></h3>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <form class="feedback-form">
                        <div class="form-group row">
                            <label for="inputName" class="col-3 col-md-2 col-form-label text-right bold hnl-red-text">Name</label>
                            <div class="col-9 col-md-10">
                            <input type="text" class="form-control hnl-red-border" id="inputName" placeholder="Your Name" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail" class="col-3 col-md-2 col-form-label text-right bold hnl-red-text">Email</label>
                            <div class="col-9 col-md-10">
                            <input type="email" class="form-control hnl-red-border" id="inputEmail" placeholder="Your Email" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputUserName" class="col-3 col-md-2 col-form-label text-right bold hnl-red-text">User Name</label>
                            <div class="col-9 col-md-10">
                            <input type="text" class="form-control hnl-red-border" id="inputUserName" placeholder="Your User Name" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputBirthDate" class="col-3 col-md-2 col-form-label text-right bold hnl-red-text">Birth Date</label>
                            <div class="col-9 col-md-10">
                            <input type="date" class="form-control hnl-red-border" id="inputBirthDate" placeholder="" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword" class="col-3 col-md-2 col-form-label text-right bold hnl-red-text">Password</label>
                            <div class="col-9 col-md-10">
                            <input type="password" class="form-control hnl-red-border" id="inputPassword" placeholder="Your Password" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputConfirmationPassword" class="col-3 col-md-2 col-form-label text-right bold hnl-red-text">Confirm Password</label>
                            <div class="col-9 col-md-10">
                            <input type="password" class="form-control hnl-red-border" id="inputConfirmationPassword" placeholder="Your Password Again" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-9 col-md-10 ml-auto">
                                <button type="submit" data-toggle="modal" data-target="#AlertSign" class="btn btn-primary hnl-red-text white-bg hnl-red-border submit-btn">Sign Up!</button>
                            </div>

                            <div class="modal fade" id="AlertSign" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title hnl-red-text" id="exampleModalCenterTitle">Sign Up!</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure you want to sign up with these information?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary hnl-red-bg light-grey-text white-border" data-dismiss="modal">Nope</button>
                                        <button type="button" class="btn btn-primary hnl-red-text white-bg hnl-red-border bold">Sure!</button>
                                    </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>

{% endblock %}