Lab/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('lab_01/', include('lab_01.urls')),
    path('lab_02/', include('lab_02.urls')),
    path('lab_03/', include('lab_03.urls')),
    path('lab_04/', include('lab_04.urls')),
    path('lab_05/', include('lab_05.urls')),
]

lab_01/urls.py
from django.urls import path
from . import views

app_name = "lab_01"

urlpatterns = [
    path('', views.my_profile, name="my_profile"),
    path('dave_profile/', views.dave_profile, name="dave_profile"),
    path('ferriyal_profile/', views.ferriyal_profile, name="ferriyal_profile")
]

lab_01/models.py
from django.db import models

# Create your models here.

lab_01/views.py
from datetime import datetime, date
from django.shortcuts import render

# Create your views here.

current_year = int(datetime.now().strftime("%Y"))

def my_profile(request):
    name = 'Jonathan Christopher Jakub'
    nickname = 'Jojo'
    npm = '1706040151'
    university = 'Faculty of Computer Science at University of Indonesia'
    hobby = 'Making fun out of everything'
    birth_date = date(1999,1,1)
    
    response = {
        "name"          : name,
        "nickname"      : nickname,
        "npm"           : npm,
        "university"    : university,
        "hobby"         : hobby,
        "age"           : calc_age(current_year, birth_date.year)
    }
    return render(request, 'lab_01/profile.html', response)

def dave_profile(request):

    response = {
        "name"          : "Dave Nathanael",
        "nickname"      : "Dave",
        "npm"           : "1706040076",
        "university"    : "Faculty of Computer Science at University of Indonesia",
        "hobby"         : "Playing Music",
        "age"           : calc_age(current_year, date(1999, 5, 8).year)
    }

    return render(request, 'lab_01/dave.html', response)


def ferriyal_profile(request):

    response = {
        "name"          : "Firriyal Bin Yahya",
        "nickname"      : "Firriyal",
        "npm"           : "1706979240",
        "university"    : "Faculty of Computer Science at University of Indonesia",
        "hobby"         : "Ngoding",
        "age"           : calc_age(current_year, date(1999, 7, 17).year)
    }

    return render(request, 'lab_01/ferriyal.html', response)

def calc_age(current_year, birth_year):
    return current_year - birth_year if birth_year <= current_year else 0

lab_01/templates/lab_01/dave.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Hello, I'm {{ nickname }}</title>
    <link rel="shortcut icon" href="{% static 'icon.png' %}">
    <link href="{% static 'lab_01/profile-styles.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>

<body>
    <ul>
        <li><a href="{% url 'lab_01:my_profile' %}">Jojo</a></li>
        <li class="active"><a href="{% url 'lab_01:dave_profile' %}">Dave</a></li>
        <li><a href="{% url 'lab_01:ferriyal_profile' %}">Ferriyal</a></li>
    </ul>

    <div class="grid-container">
        <div class="header">Hello World!</div>
        <div class="photo">
            <img src="{% static 'lab_01/dave.jpg' %}" alt="profile-photo" id="profile-photo"/>
        </div>
        <div class="bio">
            <table>
                <tr>
                    <td class="key">Name</td>
                    <td class="value">{{ name }}</td>
                </tr>
                <tr>
                    <td class="key">NPM</td>
                    <td class="value">{{ npm }}</td>
                </tr>
                <tr>
                    <td class="key">University</td>
                    <td class="value">{{ university }}</td>
                </tr>
                <tr>
                    <td class="key">Hobby</td>
                    <td class="value">{{ hobby }}</td>
                </tr>
                <tr>
                    <td class="key">Age</td>
                    <td class="value">{{ age }}</td>
                </tr>      
            </table>
        </div>  
        <div class="desc">
            <p>
                I am a student majoring Computer Science on Faculty of Computer Science, University of Indonesia. 
                I find it fun to play music, especially piano, for fun. 
                I want to be a fullstack web developer.</p>
        </div>
    </div>
</body>

</html>

lab_01/templates/lab_01/ferriyal.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Hello, I'm {{ nickname }}</title>
    <link rel="shortcut icon" href="{% static 'icon.png' %}">
    <link href="{% static 'lab_01/profile-styles.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>

<body>
    <ul>
        <li><a href="{% url 'lab_01:my_profile' %}">Jojo</a></li>
        <li><a href="{% url 'lab_01:dave_profile' %}">Dave</a></li>
        <li class="active"><a href="{% url 'lab_01:ferriyal_profile' %}">Ferriyal</a></li>
    </ul>

    <div class="grid-container">
        <div class="header">Hello World!</div>
        <div class="photo">
            <img src="{% static 'lab_01/ferriyal.jpg' %}" alt="profile-photo" id="profile-photo"/>
        </div>
        <div class="bio">
            <table>
                <tr>
                    <td class="key">Name</td>
                    <td class="value">{{ name }}</td>
                </tr>
                <tr>
                    <td class="key">NPM</td>
                    <td class="value">{{ npm }}</td>
                </tr>
                <tr>
                    <td class="key">University</td>
                    <td class="value">{{ university }}</td>
                </tr>
                <tr>
                    <td class="key">Hobby</td>
                    <td class="value">{{ hobby }}</td>
                </tr>
                <tr>
                    <td class="key">Age</td>
                    <td class="value">{{ age }}</td>
                </tr>      
            </table>
        </div>  
        <div class="desc">
            <p>Saya seorang mahasiswa yang sedang menuntut ilmu komputer.</p>
        </div>
    </div>
</body>

</html>

lab_01/templates/lab_01/profile.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Hello, I'm {{ nickname }}</title>
    <link rel="shortcut icon" href="{% static 'icon.png' %}">
    <link href="{% static 'lab_01/profile-styles.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>

<body>
    <ul>
        <li class="active"><a href="{% url 'lab_01:my_profile' %}">Jojo</a></li>
        <li><a href="{% url 'lab_01:dave_profile' %}">Dave</a></li>
        <li><a href="{% url 'lab_01:ferriyal_profile' %}">Ferriyal</a></li>
    </ul>

    <div class="grid-container">
        <div class="header">Hello World!</div>
        <div class="photo">
            <img src="{% static 'lab_01/selfie.jpg' %}" alt="profile-photo" id="profile-photo"/>
        </div>
        <div class="bio">
            <table>
                <tr>
                    <td class="key">Name</td>
                    <td class="value">{{ name }}</td>
                </tr>
                <tr>
                    <td class="key">NPM</td>
                    <td class="value">{{ npm }}</td>
                </tr>
                <tr>
                    <td class="key">University</td>
                    <td class="value">{{ university }}</td>
                </tr>
                <tr>
                    <td class="key">Hobby</td>
                    <td class="value">{{ hobby }}</td>
                </tr>
                <tr>
                    <td class="key">Age</td>
                    <td class="value">{{ age }}</td>
                </tr>      
            </table>
        </div>  
        <div class="desc">
            <p>My name is Jojo, pleased to meet you!</p>
            <span>
                I was born on January 1st, 1999 at Tangerang, Banten, Indonesia as the first son 
                of a small family that later became a family of four. 
                I spent my life growing into technology enthusiast.
                Seeking for deeper understanding and more thorough experience on IT, 
                I am looking for any opportunity to learn in order to grow into a person that is 
                able to contribute to the society and the future of technology.
            </span>
            <p>This is me, and this is why I'm here.</p>
        </div>
    </div>
</body>

</html>