Lab/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('lab_01/', include('lab_01.urls')),
    path('lab_02/', include('lab_02.urls')),
    path('lab_03/', include('lab_03.urls')),
    path('lab_04/', include('lab_04.urls')),
    path('lab_05/', include('lab_05.urls')),
]

lab_05/urls.py
from django.urls import path
from . import views

app_name = "lab_05"

urlpatterns = [
    path('', views.activity_list, name="activity_list"),
    path('activity_create/', views.activity_create, name="activity_create"),
    path('activity/<act_id>/', views.activity_details, name="activity_details"),
    path('activity/<act_id>/delete', views.activity_delete, name="activity_delete"),
    path('activity/<act_id>/note/', views.note_create, name="note"),
    path('activity_delete_all/', views.activity_delete_all, name="activity_delete_all")
]

lab_05/models.py
import calendar
from django.db import models
from django import forms
from django.forms.fields import ChoiceField
from .utils.Categories import CATEGORY_CHOICES

class Activity(models.Model):
    name = models.CharField(max_length = 100)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    place = models.CharField(max_length = 100)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10)

    def __str__(self):
        return self.name
    
    def day(self):
        return calendar.day_name[self.date.weekday()]

class Note(models.Model):
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE, related_name='notes')
    text = models.CharField(max_length=100)

    def __str__(self):
        return self.text

lab_05/forms.py
from django import forms
from . import models
from .utils.Categories import CATEGORY_CHOICES

class CreateActivity(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        "class"         : "fields",
        "required"      : True,
        "placeholder"   : "Activity Name"
    }))
    date = forms.DateField(widget=forms.DateInput(attrs={
        "class"         : "fields",
        "required"      : True,
        "placeholder"   : "Save the Date : yyyy-MM-dd"
    }))
    start_time = forms.TimeField(widget=forms.TimeInput(attrs={
        "class"         : "fields",
        "required"      : True,
        "placeholder"   : "Start at : HH:mm:ss"
    }))
    end_time = forms.TimeField(widget=forms.TimeInput(attrs={
        "class"         : "fields",
        "required"      : True,
        "placeholder"   : "Finish by : HH:mm:ss"
    }))
    place = forms.CharField(widget=forms.TextInput(attrs={
        "class"         : "fields",
        "required"      : True,
        "placeholder"   : "Where should we go?"
    }))
    category = forms.ChoiceField(choices=CATEGORY_CHOICES, widget=forms.Select(attrs={
        "class"         : "fields",
        "required"      : True,
        "placeholder"   : "Category"
    }))
    
    class Meta:
        model = models.Activity

class CreateNote(forms.ModelForm):
    class Meta:
        model = models.Note
        fields = [
            "text",
        ]

lab_05/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Activity
import datetime, time

def activity_list(request):
    activities = Activity.objects.all().order_by('date', 'start_time')
    for activity in activities:
        if check_expire(activity):
            activity.delete()
    response = {
        "title"     : "Activity List",
        "navs"      : {
            "Create New!"  : 'activity_create/',
            "Activity List": "#activity_list",
        },
        "footer"    : "Copyright of Jonathanjojo",
        "activities": activities
    }
    return render(request, 'lab_05/activity_list.html', response)

def activity_create(request):
    if request.method == "POST":
        form = forms.CreateActivity(request.POST)
        if form.is_valid(): 
            activity = Activity()
            activity.name = form.cleaned_data['name']
            activity.place = form.cleaned_data['place']
            activity.date = form.cleaned_data['date']
            activity.start_time = form.cleaned_data['start_time']
            activity.end_time = form.cleaned_data['end_time']
            activity.category = form.cleaned_data['category']
            if date_is_valid(activity.date, activity.start_time, activity.end_time):
                activity.save()
            return redirect('lab_05:activity_list')
    else:
        form = forms.CreateActivity()
    response = {
        "title"     : "Explore and Act!",
        "navs"      : {
            "Home"      : '../',
            "Act!"  : "#activity_create"
        },
        "footer"    : "Copyright of Jonathanjojo",
        "form"      : form
    }
    return render(request, 'lab_05/activity_create.html', response)

def date_is_valid(date, start_time, end_time):
    return start_time < end_time and date >= datetime.date.today()

def check_expire(activity):
    return datetime.date.today() > activity.date
        
def activity_details(request, act_id):
    activity = Activity.objects.get(id=act_id)
    if request.method == "POST":
        note_form = forms.CreateNote(request.POST)
        if note_form.is_valid(): 
            instance = note_form.save()
            return redirect('lab_05:activity_details', act_id=act_id)
    else:
        note_form = forms.CreateNote()
    response = {
        "title"     : "Here is your Activity!",
        "navs"      : {
            "Home"      : '../../',
            "Create New!": '../../activity_create/',
            "Activity"   : "#activity_details"
        },
        "footer"    : "Copyright of Jonathanjojo",
        "activity"  : activity,
        "note_form" : note_form,
    }
    return render(request, 'lab_05/activity_details.html', response)

def activity_delete(request, act_id):
    activities = Activity.objects.get(id=act_id)
    activities.delete()
    return redirect('lab_05:activity_list')

def activity_delete_all(request):
    activities = Activity.objects.all()
    activities.delete()
    return redirect('lab_05:activity_list')

def note_create(request, act_id):
    activity = Activity.objects.get(id=act_id)
    if request.method == "POST":
        note_form = forms.CreateNote(request.POST)
        if note_form.is_valid(): 
            instance = note_form.save(commit=False)
            instance.activity = activity
            instance.save()
            return redirect('lab_05:activity_details', act_id=act_id)
    else:
        note_form = forms.CreateNote()

lab_05/templates/lab_05/activity_create.html
{% extends 'lab_05/base_layout.html' %}

{% block content%}
    <div class="w-100 height-90 dark-navy-bg d-flex align-items-center section-wrapper">
        <section class="container main" id="activity_create">
            <div class="text-center">
                <h3 class="light-grey-text section-title">Create<span class="tosca-text">Activity!</span></h3>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <form class="site-form" action="{% url 'lab_05:activity_create' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="form-group row">
                                <label for="inputName" class="col-3 col-md-2 col-form-label text-right bold tosca-text">
                                    {{ field.label_tag }}
                                </label>
                                <div class="col-9 col-md-10">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="form-group row">
                            <div class="col-9 col-md-10 ml-auto">
                                <button type="submit" class="btn btn-primary tosca-text dark-navy-bg bolder tosca-border submit-btn">Create!</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

lab_05/templates/lab_05/activity_details.html
{% extends 'lab_05/base_layout.html' %}

{% block content%}
    <div class="w-100 dark-navy-bg d-flex align-items-center section-wrapper">
        <section class="container main" id="activity_details">
            <div class="text-center">
                <h2 class="tosca-text section-title">{{ activity.name }}</h2>
            </div>
            <div class="row height-50">
                <div class="col-md-9">
                    <div class="form-group row">
                        <div class="col-4 col-md-4 text-right tosca-text"><h3>Date</h3></div>
                        <div class="col-8 col-md-8 light-grey-text"><h3>{{ activity.day }}, {{ activity.date }}</h3></div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4 col-md-4 text-right tosca-text"><h3>Place</h3></div>
                        <div class="col-8 col-md-8 light-grey-text"><h3>{{ activity.place }}</h3></div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4 col-md-4 text-right tosca-text"><h3>Start Time</h3></div>
                        <div class="col-8 col-md-8 light-grey-text"><h3>{{ activity.start_time }}</h3></div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4 col-md-4 text-right tosca-text"><h3>End Time</h3></div>
                        <div class="col-8 col-md-8 light-grey-text"><h3>{{ activity.end_time }}</h3></div>
                    </div>
                    <div class="form-group row">
                        <div class="col-4 col-md-4 text-right tosca-text"><h3>Category</h3></div>
                        <div class="col-8 col-md-8 light-grey-text"><h3>{{ activity.category }}</h3></div>
                    </div>
                </div>
                <div class="col-md-3">
                    <h6 class="tosca-text">Add your Notes here :</h6>
                    <form class="site-form" action="{% url 'lab_05:note' act_id=activity.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-9 col-md-9">
                                {% for field in note_form.visible_fields %}
                                    {{ field }}
                                {% endfor %}
                            </div>
                            <div class="col-3 col-md-3 ml-auto">
                                <button type="submit" class="btn-sm btn-primary tosca-text dark-navy-bg bolder tosca-border submit-btn">Add!</button>
                            </div>
                        </div>
                    </form>
                    {% for note in activity.notes.all %}
                        <h6 class="tosca-text">- <span class="light-grey-text">{{ note.text }}</span></h6>
                    {% endfor %}
                </div>
            </div>
        </section>
    </div>
{% endblock %}

lab_05/templates/lab_05/activity_list.html
{% extends 'lab_05/base_layout.html' %}

{% block content%}
    <div class="w-100 height-90 dark-navy-bg d-flex section-wrapper">
        <section class="container main" id="activity_list">
            <div class="text-center section-title">
                <h3 class="light-grey-text">Activity<span class="tosca-text">List</span></h3>
                {% if activities.exists %}
                    <h6><a class="alert-font" data-toggle="modal" data-target="#DeleteAllAlert" href="{% url 'lab_05:activity_delete_all' %}">Delete All</a></h6>
                    <div class="modal fade" id="DeleteAllAlert" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content dark-navy-bg tosca-text light-grey-border">
                                <div class="modal-header dark-navy-border">
                                    <h5 class="modal-title hnl-red-text" id="exampleModalCenterTitle">Delete All Activities</h5>
                                    <button type="button" class="close light-grey-text" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body dark-navy-border">
                                    Are you sure you want delete all your schedules?
                                </div>
                                <div class="modal-footer dark-navy-border">
                                    <button type="button" class="btn btn-primary tosca-text dark-navy-bg tosca-border bold" data-dismiss="modal">Cancel</button>
                                    <a class="bold btn btn-secondary red-bg dark-navy-border dark-navy-text" href="{% url 'lab_05:activity_delete_all' %}">Delete All</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="row justify-contents-start">
                {% for activity in activities %}
                <div class="activity-card col-md-4">
                    <div class="activity transparent-bg rounded-edge light-grey-border card">
                        <div class="card-body">
                            <h4 class="card-title bold tosca-text">{{ activity.name }}</h4>
                            <h5 class="card-subtitle mb-2 light-grey-text">{{ activity.day }}, {{ activity.date }}</h5>
                            <h5 class="card-subtitle mb-2 light-grey-text">{{ activity.place }}, {{ activity.start_time }} - {{ activity.end_time }} </h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ activity.category }}</h6>
                            <h6 class="card-subtitle mb-2">{{ activity.notes.all.count }} notes</h6>
                            <div>
                                <h5 class="text-right">
                                    <a class="red-text" data-toggle="modal" data-target="#DeleteAlert" href="{% url 'lab_05:activity_delete' act_id=activity.id %}" class="card-link red-text">Delete</a>
                                    <a class="tosca-text" href="{% url 'lab_05:activity_details' act_id=activity.id %}" class="card-link">View</a>
                                </h5>
                            </div>
                            <div class="modal fade" id="DeleteAlert" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content dark-navy-bg tosca-text light-grey-border">
                                        <div class="modal-header dark-navy-border">
                                            <h5 class="modal-title hnl-red-text" id="exampleModalCenterTitle">Delete Activity : {{ activity.name }}</h5>
                                            <button type="button" class="light-grey-text close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body dark-navy-border">
                                            Are you sure you want delete this activity?
                                        </div>
                                        <div class="modal-footer dark-navy-border">
                                            <button type="button" class="btn btn-secondary tosca-text dark-navy-bg tosca-border bold" data-dismiss="modal">Cancel</button>
                                            <a class="bold btn btn-secondary red-bg dark-navy-border dark-navy-text" href="{% url 'lab_05:activity_delete' act_id=activity.id %}">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                    <div class="w-100 text-center">
                        <h4 class="red-text section-title">Sorry, we've come up empty :(</h4>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>

{% endblock %}